version: "3"

networks:
  gitea:
    external: false
services:
  jenkins:
    build:
      context: jenkins
    networks:
      - gitea
    user: root
    volumes: 
      # монтируем папку jenkins в контейнер
    - ./jenkins/jenkins_home:/var/jenkins_home
    ports: 
    - 8080:8080
    - 50000:50000
    restart: always
  gitea:
    build:
      context: gitea
    environment:
      - APP_NAME=Gitea
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=${ip_docker}
      - SSH_DOMAIN=${ip_docker}
      - SSH_PORT=2222
      - DOMAIN=${ip_docker}
      - HTTP_PORT=3000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gite
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/${USER}/.ssh/:/data/git/.ssh
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db
  db:
    image: mysql:8
    user: root
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./gitea/db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  kanboard:
    build: 
      context: kanboard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./kanboard/kanboard_data:/var/www/app/data
      - ./kanboard/kanboard_plugins:/var/www/app/plugins
      - ./kanboard/kanboard_ssl:/etc/nginx/ssl
