# базовый образ основан на alpine(с jdk)
FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine

# устанавливаем нужные инструменты
RUN apk add --no-cache \
  bash \
  coreutils \
  curl \
  git \
  git-lfs \
  openssh-client \
  tini \
  ttf-dejavu \
  tzdata \
  unzip

# устанавливаем аргументы приложения
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG http_port=8080
ARG agent_port=50000
ARG JENKINS_HOME=/var/jenkins_home
ARG REF=/usr/share/jenkins/ref

# устанавливаем переменные окружения
ENV JENKINS_HOME $JENKINS_HOME
ENV JENKINS_SLAVE_AGENT_PORT ${agent_port}
ENV REF $REF

# создаем основную папку jenkins_home
# добавляем владельца jenkins_home
# добавляем группу 
# добавляем пользователя
RUN mkdir -p $JENKINS_HOME \
  && chown ${uid}:${gid} $JENKINS_HOME \
  && addgroup -g ${gid} ${group} \
  && adduser -h "$JENKINS_HOME" -u ${uid} -G ${group} -s /bin/bash -D ${user}

# создаем точку монтирования для постоянного хранилища
VOLUME $JENKINS_HOME

# создаем папку для ref
RUN mkdir -p ${REF}/init.groovy.d

# задаем аргументом версию для установки jenkins
ARG JENKINS_VERSION
ENV JENKINS_VERSION ${JENKINS_VERSION:-2.289.1}

# задаем аргументом чек-сумму скачиваемого образа .war(чтобы проверить)
ARG JENKINS_SHA=70f9cc6ff1ac59aeeb831b980709a9ddb0ee70d216ee50625a8508b9840f75f2

# задаем аргументом ссылку на скачивание jenkins
ARG JENKINS_URL=https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/${JENKINS_VERSION}/jenkins-war-${JENKINS_VERSION}.war

# скачиваем jenkins той версии, которая указана в JENKINS_VERSION
# сравниваем чек-сумму 
RUN curl -fsSL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war \
  && echo "${JENKINS_SHA}  /usr/share/jenkins/jenkins.war" | sha256sum -c -

# задаем переменные окружения для апдейта
ENV JENKINS_UC https://updates.jenkins.io
ENV JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
ENV JENKINS_INCREMENTALS_REPO_MIRROR=https://repo.jenkins-ci.org/incrementals
# даем права 
RUN chown -R ${user} "$JENKINS_HOME" "$REF"

# задаем аргументом ссылку на скачивание plugin manager
ARG PLUGIN_CLI_URL=https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.9.0/jenkins-plugin-manager-2.9.0.jar

# скачиваем plugin manager
RUN curl -fsSL ${PLUGIN_CLI_URL} -o /usr/lib/jenkins-plugin-manager.jar

# указываем на необходимость открыть основной порт веб-интерфейса
EXPOSE ${http_port}

# указываем на необходимость открываем порт для присоединенного агента
EXPOSE ${agent_port}

# задаем переменную окружения для логов
ENV COPY_REFERENCE_FILE_LOG $JENKINS_HOME/copy_reference_file.log

# устанавливаем юзера
USER ${user}

# копируем необходимые скрипты в контейнер
COPY jenkins-support /usr/local/bin/jenkins-support
COPY jenkins.sh /usr/local/bin/jenkins.sh
COPY tini-shim.sh /bin/tini
COPY jenkins-plugin-cli.sh /bin/jenkins-plugin-cli

# задаем входную точку
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]

# копируем скрипт для установки плагинов в контейнер
COPY install-plugins.sh /usr/local/bin/install-plugins.sh